language: node_js
node_js:
  - "10.15.1"

cache:
  directories:
    - "node_modules"
before_install:
  - "rm -f package-lock.json && npm install"

  after_success:
  - "npm run coverage"
script:
  - "npm run test -- -u"
