export const UNAUTHENTICATED = 'UNAUTHENTICATED';
export const AUTHENTICATING = 'AUTHENTICATING';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNIN_ERROR = 'SIGNIN_ERROR';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const AUTHENTICATED = 'AUTHENTICATED';
export const INBOX_SUCCESS = 'INBOX_SUCCESS';
export const SENT_SUCCESS = 'SENT_SUCCESS';
export const UNREAD_SUCCESS = 'UNREAD_SUCCESS';
export const DASHBOARD_STATE = 'DASHBOARD_STATE';
export const SPECIFIC_MESSAGE_SUCCESS = 'SPECIFIC_MESSAGE_SUCCESS';

